---
name: "tagged-release"

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - "*"

permissions:
  attestations: write
  id-token: write
  contents: write

jobs:
  tagged-release:
    name: tagged-release
    runs-on: ubuntu-24.04
    env:
      CI_BRANCH: release
      PACKAGECLOUD_REPOSITORY: dokku/dokku
      VERSION: ${{ github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Get Repository Name
        id: repo-name
        run: |
          echo "REPOSITORY_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)" >> $GITHUB_OUTPUT
          echo "GO_VERSION=$(go mod edit -json | jq -r .Go)" >> $GITHUB_OUTPUT

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.278.0
        with:
          bundler-cache: true
          working-directory: .github

      - name: Build
        run: make build

      - name: Build Debian Packages
        run: |
          mkdir -p dist

          # copy build/$PLATFORM/coredns-docker-$ARCH to dist/coredns-docker-$PLATFORM-$ARCH
          for platform in darwin linux windows; do
            for arch in amd64 arm64 arm mips mips64le ppc64le riscv64 s390x; do
              if [ -f build/$platform/coredns-docker-$arch ]; then
                cp build/$platform/coredns-docker-$arch dist/coredns-docker-$platform-$arch
              fi
            done
          done

          cp build/windows/coredns-docker-amd64.exe dist/coredns-docker-windows-amd64.exe

          bundle exec make build/deb/${{ steps.repo-name.outputs.REPOSITORY_NAME }}_${{ github.ref_name }}_arm64.deb
          bundle exec make build/deb/${{ steps.repo-name.outputs.REPOSITORY_NAME }}_${{ github.ref_name }}_amd64.deb
          cp build/deb/*.deb dist/
        env:
          BUNDLE_GEMFILE: .github/Gemfile

      - name: Attest Build Provenance - darwin-amd64
        uses: actions/attest-build-provenance@v3.1.0
        with:
          subject-path: "dist/${{ steps.repo-name.outputs.REPOSITORY_NAME }}-darwin-amd64"

      - name: Attest Build Provenance - darwin-arm64
        uses: actions/attest-build-provenance@v3.1.0
        with:
          subject-path: "dist/${{ steps.repo-name.outputs.REPOSITORY_NAME }}-darwin-arm64"

      - name: Attest Build Provenance - linux-amd64
        uses: actions/attest-build-provenance@v3.1.0
        with:
          subject-path: "dist/${{ steps.repo-name.outputs.REPOSITORY_NAME }}-linux-amd64"

      - name: Attest Build Provenance - linux-arm
        uses: actions/attest-build-provenance@v3.1.0
        with:
          subject-path: "dist/${{ steps.repo-name.outputs.REPOSITORY_NAME }}-linux-arm"

      - name: Attest Build Provenance - linux-arm64
        uses: actions/attest-build-provenance@v3.1.0
        with:
          subject-path: "dist/${{ steps.repo-name.outputs.REPOSITORY_NAME }}-linux-arm64"

      - name: Attest Build Provenance - linux-mips
        uses: actions/attest-build-provenance@v3.1.0
        with:
          subject-path: "dist/${{ steps.repo-name.outputs.REPOSITORY_NAME }}-linux-mips"

      - name: Attest Build Provenance - linux-mips64le
        uses: actions/attest-build-provenance@v3.1.0
        with:
          subject-path: "dist/${{ steps.repo-name.outputs.REPOSITORY_NAME }}-linux-mips64le"

      - name: Attest Build Provenance - linux-ppc64le
        uses: actions/attest-build-provenance@v3.1.0
        with:
          subject-path: "dist/${{ steps.repo-name.outputs.REPOSITORY_NAME }}-linux-ppc64le"

      - name: Attest Build Provenance - linux-riscv64
        uses: actions/attest-build-provenance@v3.1.0
        with:
          subject-path: "dist/${{ steps.repo-name.outputs.REPOSITORY_NAME }}-linux-riscv64"

      - name: Attest Build Provenance - linux-s390x
        uses: actions/attest-build-provenance@v3.1.0
        with:
          subject-path: "dist/${{ steps.repo-name.outputs.REPOSITORY_NAME }}-linux-s390x"

      - name: Attest Build Provenance - windows-amd64
        uses: actions/attest-build-provenance@v3.1.0
        with:
          subject-path: "dist/${{ steps.repo-name.outputs.REPOSITORY_NAME }}-windows-amd64.exe"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: dist
          path: dist/*

      - name: Release to PackageCloud
        run: bundle exec make release-packagecloud
        env:
          BUNDLE_GEMFILE: .github/Gemfile
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true
          make_latest: "true"
